# Generated by Django 5.0.4 on 2024-10-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domiciliarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_recogida', models.CharField(max_length=200)),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=45)),
                ('fecha_hora', models.DateTimeField()),
                ('domiciliarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domiciliarios.domiciliarios')),
            ],
        ),
    ]
