# Generated by Django 5.0.4 on 2024-10-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado'), ('EN CURSO', 'En curso'), ('COMPLETADO', 'Completado'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12),
        ),
    ]
